# Generated by Django 4.2.5 on 2023-11-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countrydata',
            options={'verbose_name_plural': 'Country Population Data'},
        ),
    ]
