# Generated by Django 4.2.5 on 2023-11-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_countrydata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrydata',
            name='population',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
